### ISSUE TITLE
img als icon?

### ISSUE THREAD

**Issue by slimluccii** [DamianR2004/the-client-website#6]
https://github.com/DamianR2004/the-client-website/blob/e81717891d48bc6edbdce759fc3513a66122b8d7/index.html#L91-L92

Check out [Font Awesome](https://fontawesome.com/). Let wel op dat je de svg code kopieert. Importeer geen extra styles en scripts van Font Awesome, want dat levert performance issues op.

**Comment by DamianR2004** [comment]
Ik heb nu SVG gebruikt voor mijn sterretjes. Bedankt!
