### ISSUE TITLE
Probeer je HTML zelf te schrijven

### ISSUE THREAD

**Issue by KrijnHoetmer** [DamianR2004/the-client-website#8]
Dan kan ik je meer gerichte feedback geven, en dan krijg je meer grip op wat er (on)mogelijk is. Ga bijvoorbeeld lekker met die meter en popover dingen spelen :)

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

https://github.com/DamianR2004/the-client-website/blob/e81717891d48bc6edbdce759fc3513a66122b8d7/index.html#L2

**Comment by DamianR2004** [comment]
ik heb nu zelf de navbar en footer geschreven, bedankt!
